"""init

Revision ID: f6bb4f914739
Revises:
Create Date: 2026-09-19 04:52:14.604005

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f6bb4f914739"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_integration_settings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("igdb_client_id", sa.String(length=128), nullable=True),
        sa.Column("igdb_client_secret", sa.Text(), nullable=True),
        sa.Column("tmdb_api_key", sa.Text(), nullable=True),
        sa.Column("omdb_api_key", sa.Text(), nullable=True),
        sa.Column("tvdb_api_key", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("calendar_token", sa.String(length=64), nullable=True),
        sa.Column("steamgriddb_api_key", sa.String(length=64), nullable=True),
        sa.Column("psn_npsso_token", sa.Text(), nullable=True),
        sa.Column("psn_validated_at", sa.BigInteger(), nullable=True),
        sa.Column("retroachievements_api_key", sa.String(length=64), nullable=True),
        sa.Column("giantbomb_api_key", sa.String(length=64), nullable=True),
        sa.Column("screenscraper_ssid", sa.String(length=64), nullable=True),
        sa.Column("screenscraper_sspassword", sa.Text(), nullable=True),
        sa.Column("xbox_client_id", sa.String(length=128), nullable=True),
        sa.Column("xbox_client_secret", sa.Text(), nullable=True),
        sa.Column("gog_refresh_token", sa.Text(), nullable=True),
        sa.Column("steam_id", sa.String(length=255), nullable=True),
        sa.Column("steam_api_key", sa.String(length=64), nullable=True),
        sa.Column("retroachievements_username", sa.String(length=64), nullable=True),
        sa.Column("steam_library_synced_at", sa.BigInteger(), nullable=True),
        sa.Column("retroachievements_library_synced_at", sa.BigInteger(), nullable=True),
        sa.Column("psn_library_synced_at", sa.BigInteger(), nullable=True),
        sa.Column("steam_persona_name", sa.String(length=128), nullable=True),
        sa.Column("steam_avatar_url", sa.Text(), nullable=True),
        sa.Column("retroachievements_avatar_url", sa.Text(), nullable=True),
        sa.Column("psn_online_id", sa.String(length=128), nullable=True),
        sa.Column("psn_avatar_url", sa.Text(), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("calendar_token"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "activity_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "media_type",
            sa.Enum("MOVIE", "TV", "ANIME", name="mediatype", native_enum=False, length=10),
            nullable=False,
        ),
        sa.Column("media_id", sa.UUID(), nullable=False),
        sa.Column("media_title", sa.String(length=500), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "EPISODES_WATCHED",
                "STATUS_CHANGED",
                "RATED",
                "REWATCHED",
                name="activityeventtype",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("event_date", sa.Date(), nullable=False),
        sa.Column("count", sa.BigInteger(), nullable=False),
        sa.Column("detail", sa.String(length=200), nullable=True),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "media_type",
            "media_id",
            "event_type",
            "event_date",
            name="uq_activity_log_bucket",
        ),
    )
    op.create_index(
        "ix_activity_log_user_event_date", "activity_log", ["user_id", "event_date"], unique=False
    )
    op.create_index(op.f("ix_activity_log_user_id"), "activity_log", ["user_id"], unique=False)
    op.create_table(
        "games",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("folder_location", sa.String(length=150), nullable=False),
        sa.Column("deleted_at", sa.BigInteger(), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("sort_title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column("developer", sa.String(length=200), nullable=True),
        sa.Column("publisher", sa.String(length=200), nullable=True),
        sa.Column("series", sa.String(length=200), nullable=True),
        sa.Column("tags", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("features", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("collections", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("age_rating", sa.String(length=20), nullable=True),
        sa.Column("time_to_beat_hours", sa.Numeric(precision=6, scale=1), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=True),
        sa.Column("external_id", sa.String(length=64), nullable=True),
        sa.Column("stale_since", sa.BigInteger(), nullable=True),
        sa.Column("profiles_enabled", sa.Boolean(), nullable=False),
        sa.Column("osrs_stats_enabled", sa.Boolean(), nullable=False),
        sa.Column("parent_game_id", sa.UUID(), nullable=True),
        sa.Column("relationship_type", sa.String(length=30), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DROPPED",
                "WISHLIST",
                "BACKLOG",
                "ON_HOLD",
                "PLAYING",
                "PLAYED",
                "BEATEN",
                "MASTERED",
                name="gamestatus",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("priority", sa.String(length=20), nullable=True),
        sa.Column("favorite", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("resume_note", sa.String(length=2000), nullable=True),
        sa.Column("playtime_seconds", sa.Integer(), nullable=False),
        sa.Column("last_played_at", sa.BigInteger(), nullable=True),
        sa.Column("completion_date", sa.BigInteger(), nullable=True),
        sa.Column("purchase_date", sa.BigInteger(), nullable=True),
        sa.Column("purchase_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("purchase_price_currency_code", sa.String(length=3), nullable=True),
        sa.Column("physical_condition", sa.String(length=200), nullable=True),
        sa.Column("rating_story", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("rating_gameplay", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("rating_soundtrack", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("rating_overall", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("personal_rank", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["parent_game_id"], ["games.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_games_folder_location_active",
        "games",
        ["folder_location"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(op.f("ix_games_user_id"), "games", ["user_id"], unique=False)
    op.create_table(
        "inbox_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("filename", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("deleted_at", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_inbox_items_user_id"), "inbox_items", ["user_id"], unique=False)
    op.create_table(
        "media_lists",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("smart_rule", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("cover_media_id", sa.UUID(), nullable=True),
        sa.Column("is_system", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uq_media_lists_user_id_name"),
    )
    op.create_index(op.f("ix_media_lists_user_id"), "media_lists", ["user_id"], unique=False)
    op.create_table(
        "movies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("deleted_at", sa.BigInteger(), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("sort_title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column("runtime_minutes", sa.Integer(), nullable=True),
        sa.Column("director", sa.String(length=200), nullable=True),
        sa.Column("writer", sa.String(length=200), nullable=True),
        sa.Column("studios", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("countries", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("languages", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("genres", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("tags", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("features", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("age_rating", sa.String(length=20), nullable=True),
        sa.Column("tmdb_score", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=True),
        sa.Column("poster_url", sa.Text(), nullable=True),
        sa.Column("backdrop_url", sa.Text(), nullable=True),
        sa.Column("locked_fields", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DROPPED",
                "WISHLIST",
                "WATCHLIST",
                "BACKLOG",
                "IN_PROGRESS",
                "WATCHED",
                "FAVORITE",
                "REWATCH",
                name="moviestatus",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("priority", sa.String(length=20), nullable=True),
        sa.Column("favorite", sa.Boolean(), nullable=False),
        sa.Column("rewatches", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("rating_story", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("rating_performance", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("rating_soundtrack", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("rating_overall", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("personal_rank", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_movies_user_id"), "movies", ["user_id"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("media_type", sa.String(length=10), nullable=False),
        sa.Column("media_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("poster_url", sa.Text(), nullable=True),
        sa.Column("event_at", sa.BigInteger(), nullable=False),
        sa.Column("dedupe_key", sa.String(length=200), nullable=False),
        sa.Column("read_at", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "dedupe_key", name="uq_notifications_user_dedupe"),
    )
    op.create_index(
        "ix_notifications_user_event", "notifications", ["user_id", "event_at"], unique=False
    )
    op.create_table(
        "rewatch_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "media_type",
            sa.Enum("MOVIE", "TV", "ANIME", name="mediatype", native_enum=False, length=10),
            nullable=False,
        ),
        sa.Column("media_id", sa.UUID(), nullable=False),
        sa.Column("finished_on", sa.Date(), nullable=False),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_rewatch_logs_media_id"), "rewatch_logs", ["media_id"], unique=False)
    op.create_index(op.f("ix_rewatch_logs_user_id"), "rewatch_logs", ["user_id"], unique=False)
    op.create_table(
        "sets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("target_total", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uq_sets_user_id_name"),
    )
    op.create_index(op.f("ix_sets_user_id"), "sets", ["user_id"], unique=False)
    op.create_table(
        "tv_shows",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("deleted_at", sa.BigInteger(), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("sort_title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("first_air_date", sa.Date(), nullable=True),
        sa.Column("episode_runtime_minutes", sa.Integer(), nullable=True),
        sa.Column("creators", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("studios", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("countries", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("languages", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("genres", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("tags", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("features", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("age_rating", sa.String(length=20), nullable=True),
        sa.Column("tmdb_score", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=True),
        sa.Column("external_id", sa.String(length=50), nullable=True),
        sa.Column("is_airing", sa.Boolean(), nullable=True),
        sa.Column("next_episode_air_at", sa.BigInteger(), nullable=True),
        sa.Column("next_episode_number", sa.Integer(), nullable=True),
        sa.Column("airing_interval_days", sa.Integer(), nullable=True),
        sa.Column("poster_url", sa.Text(), nullable=True),
        sa.Column("backdrop_url", sa.Text(), nullable=True),
        sa.Column("locked_fields", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DROPPED",
                "WISHLIST",
                "WATCHLIST",
                "BACKLOG",
                "IN_PROGRESS",
                "WATCHED",
                "FAVORITE",
                "REWATCH",
                name="tvshowstatus",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("priority", sa.String(length=20), nullable=True),
        sa.Column("favorite", sa.Boolean(), nullable=False),
        sa.Column("rewatches", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("rating_story", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("rating_performance", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("rating_soundtrack", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("rating_overall", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("personal_rank", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tv_shows_user_id"), "tv_shows", ["user_id"], unique=False)
    op.create_table(
        "user_api_keys",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("key_prefix", sa.String(length=16), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("scopes", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("revoked_at", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key_hash"),
    )
    op.create_index(op.f("ix_user_api_keys_user_id"), "user_api_keys", ["user_id"], unique=False)
    op.create_table(
        "user_appearance_settings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("completion_badge_style", sa.String(length=20), nullable=False),
        sa.Column("completion_badge_color", sa.String(length=7), nullable=False),
        sa.Column("completion_badge_placement", sa.String(length=20), nullable=False),
        sa.Column("completion_badge_image_url", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "user_preferences",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "user_scan_settings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("provider_order", sa.JSON(), nullable=False),
        sa.Column("image_provider_order", sa.JSON(), nullable=False),
        sa.Column("save_developer", sa.Boolean(), nullable=False),
        sa.Column("save_publisher", sa.Boolean(), nullable=False),
        sa.Column("save_series", sa.Boolean(), nullable=False),
        sa.Column("save_tags", sa.Boolean(), nullable=False),
        sa.Column("save_features", sa.Boolean(), nullable=False),
        sa.Column("save_description", sa.Boolean(), nullable=False),
        sa.Column("save_age_rating", sa.Boolean(), nullable=False),
        sa.Column("save_release_date", sa.Boolean(), nullable=False),
        sa.Column("save_time_to_beat", sa.Boolean(), nullable=False),
        sa.Column("save_key_art", sa.Boolean(), nullable=False),
        sa.Column("save_banner", sa.Boolean(), nullable=False),
        sa.Column("save_logo", sa.Boolean(), nullable=False),
        sa.Column("save_icon", sa.Boolean(), nullable=False),
        sa.Column("provider_last_used", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "user_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_user_sessions_expires_at"), "user_sessions", ["expires_at"], unique=False
    )
    op.create_index(op.f("ix_user_sessions_user_id"), "user_sessions", ["user_id"], unique=False)
    op.create_table(
        "achievements",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("game_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("external_id", sa.String(length=200), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("icon_url", sa.Text(), nullable=True),
        sa.Column("unlocked", sa.Boolean(), nullable=False),
        sa.Column("unlocked_at", sa.BigInteger(), nullable=True),
        sa.Column("tier", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_achievements_game_id"), "achievements", ["game_id"], unique=False)
    op.create_table(
        "anime",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("deleted_at", sa.BigInteger(), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("sort_title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("first_air_date", sa.Date(), nullable=True),
        sa.Column("episode_runtime_minutes", sa.Integer(), nullable=True),
        sa.Column("studios", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("countries", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("languages", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("genres", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("tags", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("features", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("age_rating", sa.String(length=20), nullable=True),
        sa.Column("format", sa.String(length=20), nullable=True),
        sa.Column("anilist_score", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("mal_score", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=True),
        sa.Column("external_id", sa.String(length=50), nullable=True),
        sa.Column("anilist_id", sa.String(length=50), nullable=True),
        sa.Column("kitsu_id", sa.String(length=50), nullable=True),
        sa.Column("is_airing", sa.Boolean(), nullable=True),
        sa.Column("next_episode_air_at", sa.BigInteger(), nullable=True),
        sa.Column("next_episode_number", sa.Integer(), nullable=True),
        sa.Column("airing_interval_days", sa.Integer(), nullable=True),
        sa.Column("poster_url", sa.Text(), nullable=True),
        sa.Column("backdrop_url", sa.Text(), nullable=True),
        sa.Column("locked_fields", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("relations_cache", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("relations_cached_at", sa.BigInteger(), nullable=True),
        sa.Column("linked_tv_show_id", sa.UUID(), nullable=True),
        sa.Column("linked_movie_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DROPPED",
                "WISHLIST",
                "WATCHLIST",
                "BACKLOG",
                "IN_PROGRESS",
                "WATCHED",
                "FAVORITE",
                "REWATCH",
                name="animestatus",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("priority", sa.String(length=20), nullable=True),
        sa.Column("favorite", sa.Boolean(), nullable=False),
        sa.Column("rewatches", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("rating_story", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("rating_performance", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("rating_soundtrack", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("rating_overall", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("personal_rank", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["linked_movie_id"], ["movies.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["linked_tv_show_id"], ["tv_shows.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_anime_user_id"), "anime", ["user_id"], unique=False)
    op.create_table(
        "bounties",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("difficulty", sa.String(length=10), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("game_id", sa.UUID(), nullable=True),
        sa.Column("target_achievement_provider", sa.String(length=30), nullable=True),
        sa.Column("target_achievement_external_id", sa.String(length=200), nullable=True),
        sa.Column("target_collection_name", sa.String(length=120), nullable=True),
        sa.Column("progress_mode", sa.String(length=12), nullable=False),
        sa.Column("progress_value", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("progress_target", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("points_reward", sa.BigInteger(), nullable=False),
        sa.Column("required_evidence_kinds", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("target_date", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("started_at", sa.BigInteger(), nullable=True),
        sa.Column("completed_at", sa.BigInteger(), nullable=True),
        sa.Column("auto_generated", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bounties_game_id"), "bounties", ["game_id"], unique=False)
    op.create_index(op.f("ix_bounties_user_id"), "bounties", ["user_id"], unique=False)
    op.create_table(
        "game_archives",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("game_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.Column("deleted_at", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_game_archives_game_id"), "game_archives", ["game_id"], unique=False)
    op.create_table(
        "game_field_changes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("game_id", sa.UUID(), nullable=False),
        sa.Column("field_name", sa.String(length=50), nullable=False),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column("changed_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_game_field_changes_game_id"), "game_field_changes", ["game_id"], unique=False
    )
    op.create_table(
        "game_file_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("game_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("filename", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("deleted_at", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_game_file_items_game_id"), "game_file_items", ["game_id"], unique=False
    )
    op.create_table(
        "game_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=50), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "game_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("game_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("stats", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("wiseoldman_username", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("deleted_at", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_game_profiles_game_id"), "game_profiles", ["game_id"], unique=False)
    op.create_table(
        "media_list_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("list_id", sa.UUID(), nullable=False),
        sa.Column(
            "media_type",
            sa.Enum("MOVIE", "TV", "ANIME", name="mediatype", native_enum=False, length=10),
            nullable=False,
        ),
        sa.Column("media_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("added_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["list_id"], ["media_lists.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "list_id", "media_type", "media_id", name="uq_media_list_items_list_media"
        ),
    )
    op.create_index(
        op.f("ix_media_list_items_list_id"), "media_list_items", ["list_id"], unique=False
    )
    op.create_index(
        op.f("ix_media_list_items_media_id"), "media_list_items", ["media_id"], unique=False
    )
    op.create_table(
        "tv_seasons",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("show_id", sa.UUID(), nullable=False),
        sa.Column("season_number", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("episode_count", sa.Integer(), nullable=True),
        sa.Column("episodes_watched", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DROPPED",
                "WISHLIST",
                "WATCHLIST",
                "BACKLOG",
                "IN_PROGRESS",
                "WATCHED",
                "FAVORITE",
                "REWATCH",
                name="tvseasonstatus",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("air_date", sa.Date(), nullable=True),
        sa.Column("poster_url", sa.Text(), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["show_id"], ["tv_shows.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tv_seasons_show_id"), "tv_seasons", ["show_id"], unique=False)
    op.create_table(
        "anime_seasons",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("show_id", sa.UUID(), nullable=False),
        sa.Column("season_number", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("episode_count", sa.Integer(), nullable=True),
        sa.Column("episodes_watched", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DROPPED",
                "WISHLIST",
                "WATCHLIST",
                "BACKLOG",
                "IN_PROGRESS",
                "WATCHED",
                "FAVORITE",
                "REWATCH",
                name="animeseasonstatus",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("air_date", sa.Date(), nullable=True),
        sa.Column("poster_url", sa.Text(), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["show_id"], ["anime.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_anime_seasons_show_id"), "anime_seasons", ["show_id"], unique=False)
    op.create_table(
        "bounty_journal_entries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("bounty_id", sa.UUID(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["bounty_id"], ["bounties.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_bounty_journal_entries_bounty_id"),
        "bounty_journal_entries",
        ["bounty_id"],
        unique=False,
    )
    op.create_table(
        "bounty_objectives",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("bounty_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=12), nullable=False),
        sa.Column("done", sa.Boolean(), nullable=False),
        sa.Column("progress_value", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("progress_target", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("target_achievement_provider", sa.String(length=30), nullable=True),
        sa.Column("target_achievement_external_id", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["bounty_id"], ["bounties.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_bounty_objectives_bounty_id"), "bounty_objectives", ["bounty_id"], unique=False
    )
    op.create_table(
        "bounty_point_transactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("bounty_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("reason", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["bounty_id"], ["bounties.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bounty_id"),
    )
    op.create_index(
        op.f("ix_bounty_point_transactions_user_id"),
        "bounty_point_transactions",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "cards",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("game_id", sa.UUID(), nullable=False),
        sa.Column("archive_number", sa.Integer(), nullable=True),
        sa.Column("set_id", sa.UUID(), nullable=True),
        sa.Column("rarity", sa.String(length=20), nullable=True),
        sa.Column("bounty_id", sa.UUID(), nullable=True),
        sa.Column("card_customization", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["bounty_id"], ["bounties.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["set_id"], ["sets.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cards_bounty_id"), "cards", ["bounty_id"], unique=False)
    op.create_index(op.f("ix_cards_game_id"), "cards", ["game_id"], unique=False)
    op.create_index(op.f("ix_cards_set_id"), "cards", ["set_id"], unique=False)
    op.create_index(op.f("ix_cards_user_id"), "cards", ["user_id"], unique=False)
    op.create_table(
        "game_archive_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("archive_id", sa.UUID(), nullable=False),
        sa.Column("filename", sa.String(length=500), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("uploaded_at", sa.BigInteger(), nullable=False),
        sa.Column("deleted_at", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(["archive_id"], ["game_archives.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_game_archive_versions_archive_id"),
        "game_archive_versions",
        ["archive_id"],
        unique=False,
    )
    op.create_table(
        "game_checklist_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("game_id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("done", sa.Boolean(), nullable=False),
        sa.Column("is_header", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Float(), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("deleted_at", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["profile_id"], ["game_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_game_checklist_items_game_id"), "game_checklist_items", ["game_id"], unique=False
    )
    op.create_index(
        op.f("ix_game_checklist_items_profile_id"),
        "game_checklist_items",
        ["profile_id"],
        unique=False,
    )
    op.create_table(
        "game_profile_stat_snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("stats", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("xp", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("kc", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("recorded_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["profile_id"], ["game_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_game_profile_stat_snapshots_profile_id"),
        "game_profile_stat_snapshots",
        ["profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_game_profile_stat_snapshots_recorded_at"),
        "game_profile_stat_snapshots",
        ["recorded_at"],
        unique=False,
    )
    op.create_table(
        "media_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("game_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("filename", sa.String(length=300), nullable=False),
        sa.Column("tags", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("linked_achievement_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("deleted_at", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["linked_achievement_id"], ["achievements.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["profile_id"], ["game_profiles.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_media_items_game_id"), "media_items", ["game_id"], unique=False)
    op.create_table(
        "tv_episodes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("season_id", sa.UUID(), nullable=False),
        sa.Column("episode_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("air_date", sa.Date(), nullable=True),
        sa.Column("runtime_minutes", sa.Integer(), nullable=True),
        sa.Column("still_url", sa.Text(), nullable=True),
        sa.Column("watched", sa.Boolean(), nullable=False),
        sa.Column("rating", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("air_at", sa.BigInteger(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["season_id"], ["tv_seasons.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tv_episodes_season_id"), "tv_episodes", ["season_id"], unique=False)
    op.create_table(
        "anime_episodes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("season_id", sa.UUID(), nullable=False),
        sa.Column("episode_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("air_date", sa.Date(), nullable=True),
        sa.Column("runtime_minutes", sa.Integer(), nullable=True),
        sa.Column("still_url", sa.Text(), nullable=True),
        sa.Column("watched", sa.Boolean(), nullable=False),
        sa.Column("rating", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("air_at", sa.BigInteger(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["season_id"], ["anime_seasons.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_anime_episodes_season_id"), "anime_episodes", ["season_id"], unique=False
    )
    op.create_table(
        "bounty_evidence",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("bounty_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=12), nullable=False),
        sa.Column("media_item_id", sa.UUID(), nullable=True),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["bounty_id"], ["bounties.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["media_item_id"], ["media_items.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_bounty_evidence_bounty_id"), "bounty_evidence", ["bounty_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bounty_evidence_bounty_id"), table_name="bounty_evidence")
    op.drop_table("bounty_evidence")
    op.drop_index(op.f("ix_anime_episodes_season_id"), table_name="anime_episodes")
    op.drop_table("anime_episodes")
    op.drop_index(op.f("ix_tv_episodes_season_id"), table_name="tv_episodes")
    op.drop_table("tv_episodes")
    op.drop_index(op.f("ix_media_items_game_id"), table_name="media_items")
    op.drop_table("media_items")
    op.drop_index(
        op.f("ix_game_profile_stat_snapshots_recorded_at"), table_name="game_profile_stat_snapshots"
    )
    op.drop_index(
        op.f("ix_game_profile_stat_snapshots_profile_id"), table_name="game_profile_stat_snapshots"
    )
    op.drop_table("game_profile_stat_snapshots")
    op.drop_index(op.f("ix_game_checklist_items_profile_id"), table_name="game_checklist_items")
    op.drop_index(op.f("ix_game_checklist_items_game_id"), table_name="game_checklist_items")
    op.drop_table("game_checklist_items")
    op.drop_index(op.f("ix_game_archive_versions_archive_id"), table_name="game_archive_versions")
    op.drop_table("game_archive_versions")
    op.drop_index(op.f("ix_cards_user_id"), table_name="cards")
    op.drop_index(op.f("ix_cards_set_id"), table_name="cards")
    op.drop_index(op.f("ix_cards_game_id"), table_name="cards")
    op.drop_index(op.f("ix_cards_bounty_id"), table_name="cards")
    op.drop_table("cards")
    op.drop_index(
        op.f("ix_bounty_point_transactions_user_id"), table_name="bounty_point_transactions"
    )
    op.drop_table("bounty_point_transactions")
    op.drop_index(op.f("ix_bounty_objectives_bounty_id"), table_name="bounty_objectives")
    op.drop_table("bounty_objectives")
    op.drop_index(op.f("ix_bounty_journal_entries_bounty_id"), table_name="bounty_journal_entries")
    op.drop_table("bounty_journal_entries")
    op.drop_index(op.f("ix_anime_seasons_show_id"), table_name="anime_seasons")
    op.drop_table("anime_seasons")
    op.drop_index(op.f("ix_tv_seasons_show_id"), table_name="tv_seasons")
    op.drop_table("tv_seasons")
    op.drop_index(op.f("ix_media_list_items_media_id"), table_name="media_list_items")
    op.drop_index(op.f("ix_media_list_items_list_id"), table_name="media_list_items")
    op.drop_table("media_list_items")
    op.drop_index(op.f("ix_game_profiles_game_id"), table_name="game_profiles")
    op.drop_table("game_profiles")
    op.drop_table("game_links")
    op.drop_index(op.f("ix_game_file_items_game_id"), table_name="game_file_items")
    op.drop_table("game_file_items")
    op.drop_index(op.f("ix_game_field_changes_game_id"), table_name="game_field_changes")
    op.drop_table("game_field_changes")
    op.drop_index(op.f("ix_game_archives_game_id"), table_name="game_archives")
    op.drop_table("game_archives")
    op.drop_index(op.f("ix_bounties_user_id"), table_name="bounties")
    op.drop_index(op.f("ix_bounties_game_id"), table_name="bounties")
    op.drop_table("bounties")
    op.drop_index(op.f("ix_anime_user_id"), table_name="anime")
    op.drop_table("anime")
    op.drop_index(op.f("ix_achievements_game_id"), table_name="achievements")
    op.drop_table("achievements")
    op.drop_index(op.f("ix_user_sessions_user_id"), table_name="user_sessions")
    op.drop_index(op.f("ix_user_sessions_expires_at"), table_name="user_sessions")
    op.drop_table("user_sessions")
    op.drop_table("user_scan_settings")
    op.drop_table("user_preferences")
    op.drop_table("user_appearance_settings")
    op.drop_index(op.f("ix_user_api_keys_user_id"), table_name="user_api_keys")
    op.drop_table("user_api_keys")
    op.drop_index(op.f("ix_tv_shows_user_id"), table_name="tv_shows")
    op.drop_table("tv_shows")
    op.drop_index(op.f("ix_sets_user_id"), table_name="sets")
    op.drop_table("sets")
    op.drop_index(op.f("ix_rewatch_logs_user_id"), table_name="rewatch_logs")
    op.drop_index(op.f("ix_rewatch_logs_media_id"), table_name="rewatch_logs")
    op.drop_table("rewatch_logs")
    op.drop_index("ix_notifications_user_event", table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_movies_user_id"), table_name="movies")
    op.drop_table("movies")
    op.drop_index(op.f("ix_media_lists_user_id"), table_name="media_lists")
    op.drop_table("media_lists")
    op.drop_index(op.f("ix_inbox_items_user_id"), table_name="inbox_items")
    op.drop_table("inbox_items")
    op.drop_index(op.f("ix_games_user_id"), table_name="games")
    op.drop_index(
        "ix_games_folder_location_active",
        table_name="games",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("games")
    op.drop_index(op.f("ix_activity_log_user_id"), table_name="activity_log")
    op.drop_index("ix_activity_log_user_event_date", table_name="activity_log")
    op.drop_table("activity_log")
    op.drop_table("users")
    op.drop_table("app_integration_settings")
    # ### end Alembic commands ###
